services:
  static-signs:
    build:
      context: ./static-signs
      dockerfile: Dockerfile
    container_name: talk2dhand-static-signs-dev
    ports:
      - "8000:8000"
    volumes:
      # Enable hot-reload for development
      - ./static-signs/simple_server.py:/app/simple_server.py
      - ./static-signs/run_app.py:/app/run_app.py
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0
    restart: unless-stopped
    networks:
      - talk2dhand-network

  dynamic-phrases:
    build:
      context: ./dynamic-phrases
      dockerfile: Dockerfile
    container_name: talk2dhand-dynamic-phrases-dev
    ports:
      - "5008:5008"
    volumes:
      # Enable hot-reload for development
      - ./dynamic-phrases/app.py:/app/app.py
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - talk2dhand-network

networks:
  talk2dhand-network:
    driver: bridge